In [1]:
import numpy as np
import random
def fact(n):
    return np.math.factorial(n)
def combinations(k,n):
    return int(fact(n)/(fact(k)*fact(n-k)))

## 1. Из колоды в 52 карты извлекаются случайным образом 4 карты.

### a) Найти вероятность того, что все карты – крести. 

$C_n^k = C_{52}^4 = \frac{52!}{4!(52-4)!} = 270725- это\,количество\,сочетаний \,любых \,4 \,карт \,из \,52$

In [33]:
combinations(4, 52)

270725

В колоде 4 масти => крести из них 52/4 = 13 карт

$C_{13}^4 = \frac{13!}{4!(13-4)!} = 715 - это \,количество \,сочетаний \,крести \,из \,4 \,карт$

In [34]:
combinations(4, 13)

715

Выходит, что число благоприятствующих исходов, что все 4 карты - крести равно 715, а общее число возможных исходов равно 270725

$Следовательно \,вероятность \,того, \,что \,все \,карты - крести = \frac{715}{270725} = 0.0026 = 0.26\%$

In [13]:
715/270725

0.0026410564225690276

Проверим

In [4]:
iterations = 10**8
profit = 0
four_cards = 0
count = 0
while count < iterations:
    for i in range(4):
        if random.randint(1, 52) <= 13:
            four_cards += 1
#             print(four_cards)
    if four_cards == 4:
#         print(f'profit = {profit}')
        profit += 1
    four_cards = 0
    count += 1
#     print(count)
    if not count%(iterations/10) and count >= iterations/10:
        print(f'count = {count}')
# print(f'{profit} {iterations} {profit/iterations}')
print(f'Итог: {round(profit/iterations*100, 2)}% cравниваем с полученным результатом 0.26%')

count = 10000000
count = 20000000
count = 30000000
count = 40000000
count = 50000000
count = 60000000
count = 70000000
count = 80000000
count = 90000000
count = 100000000
Итог: 0.39% cравниваем с полученным результатом 0.26%


### б) Найти вероятность, что среди 4-х карт окажется хотя бы один туз.

$C_{48}^3 = 17296$ - это количество сочетаний из трех карт без тузов из 48 карт

In [7]:
combinations(3, 48)

17296

#### Количество сочетаний трех карт с каждым из тузов равно 17296*4 = 69184

In [8]:
17296*4

69184

$C_{48}^2 = 1128 - это \,количество \,сочетаний \,из \,двух \,карт \,без \,тузов \,из \,48 \,карт$

In [9]:
combinations(2, 48)

1128

$C_{4}^2 = 6 - это \,количество \,сочетаний \,из \,двух \,тузов \,из \,всех \,четырех \,тузов$

In [11]:
combinations(2, 4)

6

#### Количество сочетаний двух карт с двумя тузами равно 1128*6 = 6768

In [12]:
1128*6

6768

$C_{4}^3 = 4 - это \,количество \,сочетаний \,из \,трех \,тузов$

In [19]:
combinations(3, 4)

4

#### Количество сочетаний одной карты с тремя тузами равно 48*4 = 192

In [14]:
48*4

192

#### + еще одно сочетание всех четырех тузов

## Значит количество сочетаний 4 карт с одним, двумя, тремя и четырьмя тузами равно 69184 + 6768 + 192 + 1 = 76145

In [20]:
69184+6768+192+1

76145

А всего сочетаний 4 карт из 52 равно 270725

$=> вероятность, \,что \,среди \,4-х \,карт \,окажется \,хотя \,бы \,один \,туз = \frac{76145}{270725} = 0.28 = 28\%$

In [21]:
76145/270725

0.2812632745405855

In [2]:
iterations = 10**8
profit = 0
ace = 0
count = 0
while count < iterations:
    for i in range(4):
        if random.randint(1, 52) == 13 or random.randint(1, 52) == 26 or random.randint(1, 52) == 39 or random.randint(1, 52) == 52:
            ace += 1
    if ace:
#         print(f'profit = {profit}')
        profit += 1
    ace = 0
    count += 1
    if not count%(iterations/10) and count >= iterations/10:
        print(f'count = {count}')
# print(f'{profit} {iterations} {profit/iterations}')
print(f'Итог: {round(profit/iterations*100, 2)}% cравниваем с полученным результатом 28%')

count = 10000000
count = 20000000
count = 30000000
count = 40000000
count = 50000000
count = 60000000
count = 70000000
count = 80000000
count = 90000000
count = 100000000
Итог: 26.71% cравниваем с полученным результатом 28%


### Что-то у меня получаются слишком различные результаты с экспериментами (((

## 2. На входной двери подъезда установлен кодовый замок, содержащий десять кнопок с цифрами от 0 до 9. Код содержит три цифры, которые нужно нажать одновременно. Какова вероятность того, что человек, не знающий код, откроет дверь с первой попытки?

In [2]:
iterations = 10**8
print(f'{round((1/10)*(1/9)*(1/8)*100, 2)}%')
code = []
profit = 0
while len(code)<3:
    value = random.randint(0,9)
    if not len(code):
        code.append(value)
    elif not code.count(value):
        code.append(value)
print(f'code = {code}')
count = 0
def check_equality(list_1, list_2):
    list_1.sort()
    list_2.sort()
    if list_1 == list_2:
        return True
    else:
        return False
while count < iterations:
    input_code = []
    while len(input_code)<3:
        value = random.randint(0,9)
        if not len(input_code):
            input_code.append(value)
        elif not input_code.count(value):
            input_code.append(value)
#     print(f'input_code = {input_code}')
    if check_equality(code, input_code):
        profit += 1
#         print('!!!!!!!!PROFIT!!!!!!!!! {profit} | {count}')
    count += 1
    if not count%(iterations/10) and count >= iterations/10:
        print(f'count = {count}')
print(f'Итог: {round(profit/iterations*100, 2)}% cравниваем с полученным результатом 0.14%')

0.14%
code = [5, 0, 6]
count = 10000000
count = 20000000
count = 30000000
count = 40000000
count = 50000000
count = 60000000
count = 70000000
count = 80000000
count = 90000000
count = 100000000
Итог: 0.83% Сравниваем с полученным результатом 0.14%


#### Снова результат моего эксперимента сильно отличается от полученного значения (((

## 3. В ящике имеется 15 деталей, из которых 9 окрашены. Рабочий случайным образом извлекает 3 детали. Какова вероятность того, что все извлеченные детали окрашены?

Вероятность достать окрашенную первую окрашенную деталь равна $\frac9{15}$, вторую, если первая окрашенная уже в руках $\frac8{14}$, третью $\frac7{13}$, значит вероятность достать по очереди все три окрашенные детали равна $\frac{9*8*7}{15*14*13}$ = 0.18 = 18$\%$

In [3]:
(9*8*7)/(15*14*13)

0.18461538461538463

## 4. В лотерее 100 билетов. Из них 2 выигрышных. Какова вероятность того, что 2 приобретенных билета окажутся выигрышными?

Пока не распродано ни одного билета вероятность купить первый выигрышный равна $\frac2{100}$, далее вероятность купить второй выигрышный равна $\frac1{99}$ => вероятность купить 2 выигрышных билета подряд равна $\frac2{9900}$ = 0.0002 = 0.02%

In [1]:
2/100*1/99

0.00020202020202020202